"""Real biological DNA sequences and motifs."""

# Real promoter sequences from human genes
PROMOTER_SEQUENCES = {
    'TP53': 'GGCGCGTAAAACGTGAAACCGCGGCGCGCGCCAATATTCTGCAGACTTGGCGGGGGGTACCGCGTCCGGGGTGATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGC',
    'BRCA1': 'CCGGGGGCGCGGCCGCGCGGCGCGAGATTTCCGCGGCGCGCGATCCTCGCCTCTGCAGCCAGCCGCGCGGCCGCGGCGCGAGAGCGCGCGCGACCGCGAGCTCGCGGCGCCTC',
    'TNF': 'TATAAAAGGGGGTTTTTCCCGCCTCGAGTTCGGGGCGGGGCGGGGCAGGGGTGTCCTTGGTGCTTAAGCGTGGCGTGGGGACAGGGGTGTCCTT'
}

# Real enhancer sequences
ENHANCER_SEQUENCES = {
    'SV40': 'GTGCAGCTGCAACTGCGTGCAGCTGCAACTGCGTGCAGCTGCAACTGC',
    'CMV': 'CGTGACATTGATTATTGACTAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCCTGGCTGACCGC'
}

# Real coding sequences (first 300bp) of important genes
CODING_SEQUENCES = {
    'Insulin': 'ATGGCCCTGTGGATGCGCCTCCTGCCCCTGCTGGCGCTGCTGGCCCTCTGGGGACCTGACCCAGCCGCAGCCTTTGTGAACCAACACCTGTGCGGCTCACACCTGGTGGAAGCTCTCTACCTAGTGTGCGGGGAACGAGGCTTCTTCTACACACCCAAGACCCGCCGGGAGGCAGAGGACCTGCAGGTGGGGCAGGTGGAGCTGGGCGGGGGCCCTGGTGCAGGCAGCCTGCAGCCCTTGGCCCTGGAGGGGTCCCTGCAGAAGCGTGGCATTGTGGAACAATGCTGTACCAGCATCTGCTCCCTCTACCAGCTGGAGAACTACTGCAACT',
    'Hemoglobin': 'ATGGTGCTGTCTCCTGCCGACAAGACCAACGTCAAGGCCGCCTGGGGTAAGGTCGGCGCGCACGCTGGCGAGTATGGTGCGGAGGCCCTGGAGAGGATGTTCCTGTCCTTCCCCACCACCAAGACCTACTTCCCGCACTTCGACCTGAGCCACGGCTCTGCCCAGGTTAAGGGCCACGGCAAGAAGGTGGCCGACGCGCTGACCAACGCCGTGGCGCACGTGGACGACATGCCCAACGCGCTGTCCGCCCTGAGCGACCTGCACGCGCACAAGCTTCGGGTGGACCCGGTCAACTTCAAGCTCCTAAGCCACTGCCTGCTGGTGACCCTGGCCG',
    'P53': 'ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCT'
}

# Real regulatory elements and binding sites
REGULATORY_ELEMENTS = {
    'TATA_box': 'TATAAA',
    'CAAT_box': 'CCAAT',
    'GC_box': 'GGGCGG',
    'CpG_island': 'CGCGCGCGCGCG',
    'Kozak_sequence': 'GCCACC',
    'Splice_donor': 'GTAAGT',
    'Splice_acceptor': 'TTTCAG',
    'Poly_A_signal': 'AATAAA'
}

# Common transcription factor binding sites
TF_BINDING_SITES = {
    'NF_kB': 'GGGACTTTCC',
    'AP1': 'TGACTCA',
    'SP1': 'GGGCGG',
    'CREB': 'TGACGTCA',
    'E_box': 'CACGTG'
}

def get_real_sequence(gene_name: str) -> str:
    """Get real coding sequence for a specific gene."""
    return CODING_SEQUENCES.get(gene_name, CODING_SEQUENCES['P53'])

def get_promoter(gene_name: str) -> str:
    """Get real promoter sequence for a specific gene."""
    return PROMOTER_SEQUENCES.get(gene_name, PROMOTER_SEQUENCES['TP53'])